name: pjdfstest
on: [push, pull_request]
env:
  CARGO_TERM_COLOR: always
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy tikv cluster
        run: docker-compose -f ci/tikv-cluster-docker-compose.yaml up -d
      - name: Stat
        run: docker-compose -f ci/tikv-cluster-docker-compose.yaml ps
      - name: Install packages
        run: |
          sudo apt update
          sudo apt install -y libfuse-dev libfuse3-dev build-essential autoconf automake perl
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Build
        run: cargo build --features "binc" --no-default-features --all --release
      - name: Mount
        run: |
          mkdir mnt
          target/release/mount -t tifs tifs:127.0.0.1:2379 mnt
      - name: Build pjdfstest
        run: |
          git clone https://github.com/pjd/pjdfstest.git
          cd pjdfstest
          autoreconf -ifs
          ./configure
          make pjdfstest
      - name: Test
        run: /
          cd $GITHUB_WORKSPACE/mnt
          prove -rv $GITHUB_WORKSPACE/pjdfstest/tests


          

